### ISSUE TITLE
revisioni editoriali

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/gesione_testo#1]
avvisamo quando tutto chiaro

**Comment by lucifero55** [comment]
<html lang="it"> = Lingua 

<meta charset="utf-8"> = caratteri

<del>Quando si sbaglia bisogna sempre cancellare!</del> = Ciò tra "del" viene sbarrato

<ins cite="HTML and XHTML: The Definitive Guide, O'Reilly Ed."
           datetime="2016-01-30T15:03+01:00" = ... Non ho capito

**Comment by FabioZTessitore** [comment]
prima di tutto non usare i tag qui perché sparisce il testo

`lang` serve per la lingua, ok
`charset` è il set di caratteri, ok
`del` serve a sbarrare del testo che si vuole cancellare, ma che deve rimanere visibile
`ins` serve al contrario a segnare il testo nuovo che viene inserito.
`cite` e `datetime` sono attributi di `ins`. Il primo serve a dire da dove hai preso le informazioni che hai aggiunto, il secondo la data e l'ora della modifica

**Comment by lucifero55** [comment]
perchè messi li data cite e datatime? Non sarebbe più ordinato metterli all'inizio o alla fine della pagina?

**Comment by FabioZTessitore** [comment]
sono attributi del tag ins. Vatti a rivedere il concetto di attributo

**Comment by lucifero55** [comment]
Ok ho capito, ma... se non si vedono hanno un senso? :P

**Comment by FabioZTessitore** [comment]
si, le informazioni non sono solo da visualizzare. Immagina di fare un programmino che quando il mouse va sulla modifica mostra qualcosa
