### ISSUE TITLE
Il testo

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/gesione_testo#2]
testo

**Comment by lucifero55** [comment]
Conviene mettere sempre div invece di usare br o sbaglio?

**Comment by FabioZTessitore** [comment]
hanno un significato diverso.
`div` crea una divisione, cioè un blocco di "cose"

`br` rompe il testo per andare a capo, ma non crea un altro paragrafo o un altro blocco

**Comment by lucifero55** [comment]
Ah ok non ci avevo fatto caso, capito
