### ISSUE TITLE
caratteri speciali

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/gesione_testo#4]
Alcuni caratteri hanno un significato speciale
e non possono essere inseriti direttamente nelle pagine Web.

I simboli `<` e `>` per esempio servono a delimitare i tag.

In questi casi si utilizzano dei codici:
```html
&lt;    (less than)     minore
&gt;    (greater than)  maggiore
&amp;   (ampersand)     &
```

Anche per le lettere accentate vale un discorso analogo:
```
&eacute;  é
&egrave;  è
&ograve;  ò
...
```

**Comment by lucifero55** [comment]
chiaro
