### ISSUE TITLE
esercitazione: il linguaggio C

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/gesione_testo#5]
Cerca di ottenere questo risultato

![linguaggioc_pt1](https://cloud.githubusercontent.com/assets/3002194/13862728/4df8cf44-ec95-11e5-818a-57250d43b653.png)
![linguaggioc_pt2](https://cloud.githubusercontent.com/assets/3002194/13862729/515ad3f8-ec95-11e5-940a-62c85f1ffc28.png)

**Comment by lucifero55** [comment]
fatto

**Comment by lucifero55** [comment]
ma va bene che non si visualizzi "stdio.h"? 

Ps non vi vede neanche nella immagine

**Comment by FabioZTessitore** [comment]
che ti ho detto a proposito dei caratteri speciali?

**Comment by lucifero55** [comment]
giusto, modifico subito

**Comment by lucifero55** [comment]
fatto

**Comment by FabioZTessitore** [comment]
devi aggiustare la firma in basso e il codice.
Vatti a vedere la issue #4

**Comment by lucifero55** [comment]
lo farò.
(guardi Mr. Robot)

**Comment by FabioZTessitore** [comment]
muoviti

**Comment by lucifero55** [comment]
Non ho capito cosa aggiungere/modificare

**Comment by FabioZTessitore** [comment]
la firma in basso si fa con un tag apposito.
Il codice del programma di esempio pure.
Vai a vedere la issue #3 per informazioni

**Comment by FabioZTessitore** [comment]
sei riuscito a trovare i tag?

**Comment by FabioZTessitore** [comment]
mi spiace ma non ci siamo.
il codice non si fa con samp.
La firma invece va bene con address, ma non è il tuo nome. C'era già.

**Comment by FabioZTessitore** [comment]
ok

per evitare di mettere tutti quei `br` dentro a `code` puoi usare anche `pre` (in congiunzione con `code` intendo)
