### ISSUE TITLE
id e classi

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/gesione_testo#6]
ho caricato posts.html
dimmi se ti è chiaro

**Comment by lucifero55** [comment]
Serve solo al lettore del codice della pagina ho a qualche utilità?

**Comment by lucifero55** [comment]
https://www.youtube.com/watch?v=Ukg_U3CnJWI
Bel video

**Comment by lucifero55** [comment]
Domanda:
"Si può scrivere un programma che permetta di mandare automaticamente alcune istruzioni da terminale? A volte mi ritrovo a fare sempre le stesse operazioni e a raggrupparle in un programma a mo' di funzione mi sembra molto agevole"

**Comment by FabioZTessitore** [comment]
se tu non hai voglia di aprire gmail io perché dovrei aver voglia di rispondere qui?

**Comment by lucifero55** [comment]
Non ho capito se servono effettivamente a qualcosa i div

**Comment by FabioZTessitore** [comment]
servono. Sono contenitori.
Ad esempio un `<div class="post-title">` è un contenitore per tutte le informazioni riguardanti il titolo di un post.
Un `<div class="post">` invece è un contenitore per un post completo (titolo, autore, ecc ecc)

E così via
