### ISSUE TITLE
Tweets

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/gesione_testo#7]
Crea una pagina tweets.html in cui sia presente
una lista di tweets. Scegli con attenzione gli
elementi di cui e' formato un singolo tweet.

**Comment by lucifero55** [comment]
Cosa si intende per tweet?

**Comment by FabioZTessitore** [comment]
non conosci twitter?

**Comment by lucifero55** [comment]
si, ma non lo utilizzo

**Comment by FabioZTessitore** [comment]
ma un tweet sai cos'è però

**Comment by lucifero55** [comment]
quando mandi un messaggio e arriva a tutto la plebe che ti segue...?

**Comment by FabioZTessitore** [comment]
eh, vai sul sito e cerca di capire come si potrebbe fare in termini di contenitori

**Comment by lucifero55** [comment]
Qualcosa del genere?

**Comment by FabioZTessitore** [comment]
Quasi.

Questa roba qui:
```html
<div class="Name-User">Paolo Il Bello</div>
<div class="Tweet-Text">Oggi ho mangiato un'anatra</div>
<div class="Tweet-Popolarity">Retweet: 0  Mi piace: 0</div>
```
che cos'è? a me sembrerebbe un tweet, non un tpaolo. Quando metti una classe immagina di dire a quale "categoria" appartiene quel contenitore

**Comment by lucifero55** [comment]
Con TPaolo volevo intentere Tweet di Paolo

**Comment by FabioZTessitore** [comment]
lo avevo capito ma non ha senso. Un contenitore di `tweets` dovrebbe contenere una serie di `tweet`
Se poi ognuno di questi ha un identificativo univoco bene, ma la categoria è la stessa per tutti
